### ISSUE TITLE
Serious problem in comment function.

### ISSUE THREAD

**Issue by charliennnsdk** [Aniruddha-Tapas/UPES-SPE-Fest#2]
Thanks for solving problem in sharing photos, but there is a problem in comment function.

Logcat

FATAL EXCEPTION: main
                                                  Process: com.myapps.upesse.upes_spefest, PID: 31263
                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
                                                      at com.myapps.upesse.upes_spefest.ui.activity.CommentsFragment$3.onClick(CommentsFragment.java:169)
                                                      at android.view.View.performClick(View.java:5714)
                                                      at android.widget.TextView.performClick(TextView.java:10926)
                                                      at android.view.View$PerformClick.run(View.java:22589)
                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at android.os.Looper.loop(Looper.java:148)
                                                      at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Also, I can not see post in comment screen(Custom dialog)

**Comment by Aniruddha-Tapas** [comment]
Hi I have updated the code. It was the same problem. So changed 
> user.getPhotoUrl().toString()

with

> user.getPhotoUrl() != null ? user.getPhotoUrl().toString() : null

The reason you are running into these errors is that you must have signed into the app with an account that doesn't have a profile picture. Hopefully I solved the problem. Please rebuild the app and check if the same error shows up.  If it does, reopen the issue . Closing it for now.
