### ISSUE TITLE
Cannot upload image

### ISSUE THREAD

**Issue by ghost** [Aniruddha-Tapas/UPES-SPE-Fest#4]

**Comment by Aniruddha-Tapas** [comment]
Hey, I suggest you to build the app and check the error in the debugger. That might help us to identify the reason of crashing. Make sure you have the google-services.json file to build the app.

**Comment by ghost** [comment]
Have google-service.json already. No error in debugger, but after sign in, interface show no internet connection and message show "error in upload image". But there is internet in emulation device because searching in google work.

**Comment by ghost** [comment]
Same issue here, everything works until I uplosd an image, the app force closes after that.

**Comment by charliennnsdk** [comment]
Same here.
Logcat :
03-01 02:06:45.272 4104-4104/com.ydhs.ydhsrenew E/FirebaseApp: Firebase API initialization failure.
                                                               java.lang.reflect.InvocationTargetException
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                   at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1759)
                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1734)
                                                                   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:6420)
                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951)
                                                                   at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                                                                Caused by: java.lang.NoSuchMethodError: No static method zzz(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/app/com.ydhs.ydhsrenew-1/split_lib_dependencies_apk.apk)
                                                                   at com.google.android.gms.measurement.internal.zzx.zzbd(Unknown Source)
                                                                   at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source)

**Comment by ghost** [comment]
I fixed mine with going into the firebase storage and making the rules public.

**Comment by charliennnsdk** [comment]
It did work!
Thank you
